server:
  port: 9100
  context-path: /frieza

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/

spring:
  datasource:
    url: jdbc:h2:mem:piccolo;DB_CLOSE_ON_EXIT=FALSE;INIT=RUNSCRIPT FROM 'classpath:sql/region.sql'
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2
  redis:
    database: 0
    host: 192.168.1.6
    port: 6379