server:
  port: 9100
  context-path: /frieza

eureka:
  instance:
    hostname: frieza.dragon.com
    status-page-url-path: /frieza/info
  client:
    service-url:
      defaultZone: http://toriyama.dragon.com:9000/eureka/

spring:
  datasource:
    url: jdbc:mysql://localhost/quickstart?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: fuyongde
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    database: 0
    host: 192.168.1.6
    port: 6379

