server:
  port: 9200
  context-path: /piccolo

eureka:
  instance:
    hostname: piccolo.dragon.com
    status-page-url-path: /piccolo/info
  client:
    service-url:
      defaultZone: http://toriyama.dragon.com:9000/eureka/