server:
  port: 9200
  context-path: /piccolo

spring:
  activemq:
    broker-url: failover:(tcp://activemq1.dafy.com:61616,tcp://activemq2.dafy.com:61616,tcp://activemq3.dafy.com:61616)

eureka:
  instance:
    hostname: www.dragon.com
    status-page-url-path: /piccolo/info
  client:
    service-url:
      defaultZone: http://www.dragon.com:9000/eureka/