server:
  port: 9200
  context-path: /piccolo

eureka:
  instance:
    hostname: www.dragon.com
    status-page-url-path: /piccolo/info
  client:
    service-url:
      defaultZone: http://www.dragon.com:9000/eureka/