server:
  port: 9200
  context-path: /piccolo

spring:
  activemq:
    broker-url: tcp://www.dragon.com:61616

eureka:
  instance:
    hostname: www.dragon.com
    status-page-url-path: /piccolo/info
  client:
    service-url:
      defaultZone: http://www.dragon.com:9000/eureka/