-- auto Generated on 2017-08-14 16:03:07 
-- DROP TABLE IF EXISTS `password`; 
CREATE TABLE `t_password`(
    `id` INT (11) NOT NULL AUTO_INCREMENT COMMENT 'id',
    `user_id` INT (11) NOT NULL DEFAULT -1 COMMENT '用户id',
    `password` VARCHAR (128) NOT NULL DEFAULT '' COMMENT '密码',
    `salt` VARCHAR (64) NOT NULL DEFAULT '' COMMENT '随机盐',
    `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `deleted` TINYINT (3) NOT NULL DEFAULT 0 COMMENT '是否删除',
    PRIMARY KEY (`id`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT '密码表';
