-- DROP TABLE IF EXISTS `t_user`;
CREATE TABLE `t_user`(
    `id` INT (11) NOT NULL AUTO_INCREMENT COMMENT 'id',
    `username` VARCHAR (16) NOT NULL DEFAULT '' COMMENT '用户名',
    `mobile` VARCHAR (16) NOT NULL DEFAULT '' COMMENT '手机号',
    `email` VARCHAR (32) NOT NULL DEFAULT '' COMMENT 'email',
    `id_card` VARCHAR (32) NOT NULL DEFAULT '' COMMENT '身份证',
    `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'created',
    `updated` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'updated',
    `deleted` TINYINT (3) NOT NULL DEFAULT 0 COMMENT '是否删除',
    PRIMARY KEY (`id`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT '用户表';
