server:
  port: 9000

spring:
  application:
    name: toriyama
  http:
    encoding:
      charset: UTF-8

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/