server:
  port: 9600
  context-path: /goku

eureka:
  instance:
    hostname: www.dragon.com
    status-page-url-path: /goku/info
  client:
    service-url:
      defaultZone: http://www.dragon.com:9000/eureka/

spring:
  datasource:
    url: jdbc:mysql://www.dragon.com/quickstart?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: fuyongde
    driver-class-name: com.mysql.jdbc.Driver