server:
  port: 9300
  context-path: /kuririn

eureka:
  instance:
    hostname: kuririn.dragon.com
    status-page-url-path: /kuririn/info
  client:
    service-url:
      defaultZone: http://toriyama.dragon.com:9000/eureka/